-- main
require('core.plugins')
require('core.mappings')
require('core.colors')
require('core.configs')
-- plugins
require('plugins.neotree')
require('plugins.treesitter')
require('plugins.lsp')
require('plugins.mason')
require('plugins.telescope')
require('plugins.autopairs')
require('plugins.buffline')
require('plugins.comments')
require('plugins.gitsigns')
require('plugins.lualine')
require('plugins.whichkey')
require('plugins.presence')
require('plugins.vimtex')
